spring.application.name=backend
logging.level.org.springframework.security=DEBUG

# Configurazione per database H2 persistente su file
# Il file del database verrà creato nella cartella 'data' all'interno del tuo progetto
spring.datasource.url=jdbc:h2:file:./data/oleum_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Imposta la piattaforma per il dialetto Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Aggiorna lo schema automaticamente senza cancellare i dati a ogni avvio
spring.jpa.hibernate.ddl-auto=update 
#Hybernate con la sua policy rende il database H2 persistente, senza cancellare i dati a ogni avvio dell'applicazione.


#utilizzo JPA (Jakarta Persistence API) che è una specifica (insieme di regole) per la gestione della persistenza dei dati in Java. 
#JPA è un'API standard che permette di mappare le classi Java agli oggetti del database relazionale, facilitando l'interazione con
# il database senza dover scrivere manualmente query SQL complesse.
#HYBERNATE è un'implementazione concreta di JPA, che fornisce le funzionalità necessarie per gestire la persistenza dei dati
# in un'applicazione Java.